#!/bin/sh

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo '<security-notice-list xmlns="http://security.libvirt.org/xmlns/security-notice-list/1.0">'
for n in $@
do
  n=`echo $n | sed -e 's,notices/,,'`
  echo "  <security-notice name='$n'/>"
done
echo '</security-notice-list>'
